development:
  adapter: postgresql
  encoding: unicode
  database: car_reservation_development
  pool: 5
  host: localhost
  username: postgres
  password: adebowale

test:
  adapter: postgresql
  encoding: unicode
  database: car_reservation_test
  pool: 5
  username: postgres
  password: adebowale

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>